### ISSUE TITLE
ex3 : overloading is not allowed in Minijava

### ISSUE THREAD

**Issue by dan-blank** [dan-blank/JavaToMIPS_Testcases#8]
@SgnJp some of your ok-testcases contain overloading, which is not allowed in MiniJava, source: https://proglang.informatik.uni-freiburg.de/teaching/compilerbau/2016ws/ex2.pdf

Sorry that this comes up so late :/

**Comment by SgnJp** [comment]
Thanks, I commited new version, hope it is correct

**Comment by DanielJBlank** [comment]
Works now (^. ^)b
